### ISSUE TITLE
Event handlers issue

### ISSUE THREAD

**Issue by dy** [github/template-parts#23]
If we try to pass event as template part we get syntax error:
```html
<div onclick="{{ handler }}">Clickme</div>
...
```

> Uncaught SyntaxError: Unexpected token '{'

**Comment by keithamus** [comment]
I'm unable to reproduce this; could you please provide a Reduced Test Case demonstrating this failure?

**Comment by dy** [comment]
Ok, can't reproduce it too.
I guess the expected behavior (attaching handler instead of inserting function body as string) can be reached via custom processor.

**Comment by keithamus** [comment]
> can be reached via custom processor.

Yes this is how we're doing it for now.
