### ISSUE TITLE
Parser: nested braces case

### ISSUE THREAD

**Issue by dy** [github/template-parts#38]
There might be cases with nested double braces, like:
```html
<my-element title={{ "Your balance: {{ balance }}" }}></my-element>
```
String expressions don't seem to be prohibited by proposal, do they?

Fix for the parser is fairly simple:
```js
export function* parse(text: string): Iterable<Token> {
  let value = ''
  let tokenStart = 0
  let open = 0
  for (let i = 0; i < text.length; i += 1) {
    if (text[i] === '{' && text[i + 1] === '{' && text[i - 1] !== '\\' ) {
      if (++open === 1) {
        if (value) yield {type: 'string', start: tokenStart, end: i, value}
        value = '{{'
        tokenStart = i
        i += 2
      }
    } else if (text[i] === '}' && text[i + 1] === '}' && text[i - 1] !== '\\' ) {
      if (!--open) {
        yield {type: 'part', start: tokenStart, end: i + 2, value: value.slice(2).trim()}
        value = ''
        i += 2
        tokenStart = i
      }
    }
    value += text[i] || ''
  }
  if (value) yield {type: 'string', start: tokenStart, end: text.length, value}
}
```

**Comment by dy** [comment]
I also noticed there's `value.slice(2)` thing going on. It can also be worked around as
```diff
export function* parse(text: string): Iterable<Token> {
  let value = ''
  let tokenStart = 0
  let open = 0
  for (let i = 0; i < text.length; i += 1) {
-    if (text[i] === '{' && text[i + 1] === '{' && text[i - 1] !== '\\' ) {
+    if (text[i] === '{' && text[i + 1] === '{' && text[i - 1] !== '\\' && text[i+2]) {
      if (++open === 1) {
        if (value) yield {type: 'string', start: tokenStart, end: i, value}
-        value = '{{'
+        value = ''
        tokenStart = i
        i += 2
      }
    } else if (text[i] === '}' && text[i + 1] === '}' && text[i - 1] !== '\\' ) {
      if (!--open) {
-        yield {type: 'part', start: tokenStart, end: i + 2, value: value.slice(2).trim()}
+        yield {type: 'part', start: tokenStart, end: i + 2, value: value.trim()}
        value = ''
        i += 2
        tokenStart = i
      }
    }
    value += text[i] || ''
  }
  if (value) yield {type: 'string', start: tokenStart, end: text.length, value}
}
```

**Comment by keithamus** [comment]
I mocked up a quick test harness using code derived from the spec. Please do check if you think I have the implementation wrong:

```js
export function parseSpec(text) {
  // Let position be a position variable for template, initially pointing at the start of template.
  let position = 0
  // Let state be “initial”.
  let state = "initial"
  // Let beginningPosition be position.
  let beginningPosition = position
  // Let lastCodePoint be U+0000 NULL.
  let lastCodePoint = null
  // Let tokens be a list of pairs consisting of a type which takes a value of “string” or “part” and a string.
  let tokens = []

  // XXX: additional Lets defined in block scope lower in spec
  let codePoint = ""
  let candidateEndingPosition = 0
  
  // While position is not past the end of input:
  while(position !== text.length) {
    codePoint = text[position]
    
    // If state is “initial” and the code point is U+007B LEFT CURLY BRACKET and lastCodePoint is not U+005C REVERSE SOLIDUS,
    if (state == "initial" && codePoint === '{' && lastCodePoint !== '\\') {
      // Let state be “beginCurly”
      state = "beginCurly"
      // Let candidateEndingPosition be position.
      candidateEndingPosition = position
      // Go to step 6.iv.
    } else 
    // If state is “beginCurly”,
    if (state == "beginCurly") {
      // If the code point is U+007B LEFT CURLY BRACKET and lastCodePoint is not U+005C REVERSE SOLIDUS,
      if (codePoint === "{" && lastCodePoint !== "\\") {
        // Let state be “part”.
        state = "part"


        // Append the pair of the type “string” and the code points starting at beginningPosition and ending immediately before candidateEndingPosition to the end of tokens.
        tokens.push({
          type: "string",
          start: beginningPosition,
          end: candidateEndingPosition,
          value: text.slice(beginningPosition, candidateEndingPosition)
        })
    
        // Let beginningPosition be the next code point in template.
        beginningPosition = position + 1

        // Otherwise,
      } else {
        // Let state be “initial”.
        state = "initial"
        // Got to step 6.iv.
      }
    } else 
    // If state is “part” and the code point is U+007D RIGHT CURLY BRACKET and lastCodePoint is not U+005C REVERSE SOLIDUS,
    if (state == "part" && codePoint == "}" && lastCodePoint !== "\\") {
      // Let state be “endCurly”.
      state = "endCurly"
      // Let candidateEndingPosition be position.
      candidateEndingPosition = position
      // Go to step 6.iv.
    } else 
    // If state is “endCurly” and the code point is U+007D RIGHT CURLY BRACKET,
    if (state == "endCurly" && codePoint == "}") {
      // If the code point is U+007D RIGHT CURLY BRACKET and lastCodePoint is not U+005C REVERSE SOLIDUS,
      if (codePoint == "}" && lastCodePoint !== "\\") {
        // Let state be “initial”.
        state = "initial"

        // Let expression be the code points starting at beginningPosition and ending immediately before candidateEndingPosition.
        let expression = text.slice(beginningPosition, candidateEndingPosition)
        
        // Strip leading and trailing ASCII whitespace from expression.
        expression = expression.trim()

        // Append the pair of type “part” and expression to the end of tokens.
        tokens.push({
          type: "part",
          start: beginningPosition,
          end: candidateEndingPosition,
          value: expression
        })

      // Otherwise,
      } else {
        // Let state be “part”.
        state = "part"
        // Go to step 6.iv.
      }
    }

    // Let lastCodePoint be the current code point if lastCodePoint is not U+005C REVERSE SOLIDUS. Otherwise let lastCodePoint be U+0000 NULL.
    lastCodePoint = lastCodePoint !== "\\" ? codePoint : null
    // Advance position to the next code point in template.
    position += 1
  }
  // Return tokens.
  return Object.freeze(tokens)
}
```

According to the spec:

```
`{{ "Your balance: {{ balance }}" }}`:
[
  { type: 'string', start: 0, end: 0, value: '' },
  { type: 'part', start: 2, end: 29, value: '"Your balance: {{ balance' }
]
```

This is obviously broken. We should raise it upstream and correct the spec to do the appropriate thing. I think there need to be slightly more substantial changes to the spec's algo to accommodate different inputs.

**Comment by dy** [comment]
You're right. In [DOM-Parts](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/DOM-Parts.md) they relegate parsing to user-land, so I had an impression that _Template-Parts_ is getting obsolete. There seems to be other mentioned parsing problems (`<table>{{data}}</table>`, `<svg width="{{ width }}">`), also - they're trying to make template parts independent of `<template>` element, indeed there's nothing stopping from inserting parts to any element.
I thought in _github/template-parts_ you provide more meaningful minimal implementation than spec. [Template-instantiation-polyfill](https://github.com/bennypowers/template-instantiation-polyfill) already follows spec very closely, and it looks humongous.

**Comment by keithamus** [comment]
> . In [DOM-Parts](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/DOM-Parts.md) they relegate parsing to user-land, so I had an impression that _Template-Parts_ is getting obsolete.

I believe the intent is not to obsolete the parsing step. The intent is to ship minimally viable primitives which should be easier to agree on. The complete proposal of Template Parts is too big to reasonably be implemented in one go without massive amounts of bike shedding and lack of consensus (See ES4 harmony :wink:).

One thing we all seem to agree on is that there should be a set of objects which represent an interchangeable pointer to the DOM. This is what the DOM Parts spec is. I believe once that has been settled and specified, the Template Parts spec (and this repository) will update to reference/include that spec.

> I thought in github/template-parts you provide more meaningful minimal implementation than spec. 

That's definitely the case. Our intent is to provide something that we can use in production (which we do) but something which stays (mostly) compatible with the proposed specs so that once ratified, we can simply delete this repository and rely on the native Web Platform.

The careful line we need to tread is _how_ we diverge. For example we don't monkeypatch `HTMLTemplateElement.prototype.createInstance` because that would cause more problems than it would solve. 

I think it's still worth raising these issues upstream to see what the solution may be. I think for a step like this it's likely the proposed parser spec can change without much issue, and doing so will keep us still closely aligned, rather than divergant. 

To be clear: I'm still interested in pursuing changes to the parser to make it work for cases like this. I'd like to _also_ escalate upstream.

**Comment by dy** [comment]
I'm saying your parser implementation looks more elegant for me, same as other parts.
I'm working on [alternative template-parts](https://github.com/spectjs/tpl-parts/blob/main/src/api.js) implementation, using yours and @bennypowers implementation as ref. And following spec code is much harder, it seems a bit unnatural.
