### ISSUE TITLE
Processor with expression syntax support

### ISSUE THREAD

**Issue by dy** [github/template-parts#39]
Recently I was working on tiny and performant vue-like processor for template parts, [subscript](https://github.com/spectjs/subscript).
Going to give it a try in fork of template-parts, but if you'd like to have processor kind with basic expressions syntax support, this one is a good option to have a look.
Allows syntaxes like _liquid_ and more.

**Comment by keithamus** [comment]
`subscript` looks great! I can definitely see some great use cases for it!

I'd be hesitant to bring it into this project, which I'd like to keep dependency free and keep the processors relatively independent. The default processor really serves more as an basic reference, with the idea that more advanced processors like `subscript` exist.

I'll close this for now, as I don't think there is anything actionable here based on the above.

**Comment by dy** [comment]
I guess worth mentioning here - [templize](https://github.com/spectjs/templize/blob/main/README.md) provides expression processor, compatible with github/template-parts.
