### ISSUE TITLE
processCallback call in TemplateInstance creation

### ISSUE THREAD

**Issue by dy** [github/template-parts#40]
According to the [4.3 Creating Template Parts](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/Template-Instantiation.md#43-creating-template-parts):

> 9. If there is a template create callback associated with the context object:
> i. Let createCallback be TemplateProcessCallback associated with the context object.
> ii. Invoke [[Call]] internal method of createCallback with instance, partArray, and state.
> iii. If the previous step resulted in abrupt completion, return null.
> 10. Let processCallback be the template process callback associated with the context object.
> 11. Invoke [[Call]] internal method of processCallback with instance, partArray, and state.

So on template instance creation both _createCallback_ and _processCallback_ should be called according to the spec.
I just wonder how much sense it makes.

**Comment by keithamus** [comment]
> I just wonder how much sense it makes.

We intentionally left this out because I didn't see it making sense, but in light of #41 (in addition to aligning to the spec more) I feel happy to make this change.
