### ISSUE TITLE
Published modules pathing is incorrect for `main` and `module`

### ISSUE THREAD

**Issue by cjpillsbury** [github/template-parts#60]
In the latest published version of `@github/template-parts` (`@0.5.2`)

* `main` and `module` point to `lib/index.js` and `files` also includes `lib`
* `lib/index.js` doesn't exist, but `lib/src/index.js` exists (as does `lib/test/*`, so I'm suspecting it was a build destination pathing issue?)

This means that using the default for imports will break, e.g.:

```js
import {
  TemplateInstance,
  NodeTemplatePart,
  createProcessor,
  AttributeTemplatePart,
} from '@github/template-parts';
```

Current workaround: Point directly to the intended default/main module with imports, e.g.:

```js
import {
  TemplateInstance,
  NodeTemplatePart,
  createProcessor,
  AttributeTemplatePart,
} from '@github/template-parts/lib/src/index.js';
```

**Comment by keithamus** [comment]
I think this should be fixed in `v0.5.3`. Let me know if this works for you or not 😄

**Comment by cjpillsbury** [comment]
Awesome, thanks for the quick turnaround! Will keep you posted once I pick this back up.

**Comment by cjpillsbury** [comment]
Closing since it's been fixed for _**ages**_ now.
